import {renderSpec} from './model.js?v=20261008c';
const API='https://vajlhodqxskozuxxlujv.supabase.co/functions/v1/novabyte-preview';
const KEY='sb_publishable_uT0b4y0Bex1k1QWZoyIfKg_K0pm-yS3';
const $=id=>document.getElementById(id);let mode='template',current=null,token='',busy=false,lastBrief=null;
const storage={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
async function api(path='',body){const r=await fetch(API+path,{method:body?'POST':'GET',headers:{apikey:KEY,...(body?{'Content-Type':'application/json','x-preview-session':token}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(55000)});let data;try{data=await r.json()}catch{throw Error('O serviço não respondeu. Tente novamente em instantes.')}if(!r.ok)throw Error(data.error||'Não foi possível concluir. Tente novamente.');return data;}
function status(t){$('status').textContent=t;}
function brief(){return {name:$('name').value.trim(),kind:$('kind').value,prompt:$('prompt').value.trim(),theme:$('theme').value,accent:$('accent').value};}
function fill(b){for(const k of ['name','kind','prompt','theme','accent'])if(b[k])$(k).value=b[k];}
function link(){return location.origin+location.pathname+'#p='+current.id;}
function show(data,editable){current=data;if(editable){$('theme').value=data.spec.theme;$('accent').value=data.spec.accent;}$('preview').srcdoc=renderSpec(data.spec);$('preview').hidden=false;$('empty').hidden=true;$('proposal').hidden=false;$('preview-name').textContent=data.spec.name+' · Prévia';$('mode-badge').textContent=data.mode==='ai'?'Personalizada por IA':'Prévia por modelos';$('revision-form').hidden=!editable;$('revision-help').textContent=mode==='ai'?'Descreva o ajuste desejado. Você pode usar até dois ajustes.':'No modo por modelos, os ajustes alteram aparência e cor. Use as opções acima ou escreva “claro”, “escuro” e uma cor.';const text='Olá! Criei uma prévia na NovaByte Soluções e quero um orçamento.\nProjeto: '+data.spec.name+'\nTipo: '+data.spec.kind+'\nPrévia: '+link();$('quote').href='https://wa.me/5531983771576?text='+encodeURIComponent(text);history.replaceState(null,'','#p='+data.id);}
async function generate(revision=false){if(busy||!$('brief').reportValidity())return;if(revision&&!current)return;busy=true;$('generate').disabled=true;$('revise').disabled=true;$('loading').hidden=false;status('');try{if(!token){const s=await api('',{action:'session'});token=s.token;storage.set('nb-preview-session',token);}const b=revision?{...lastBrief,theme:$('theme').value,accent:$('accent').value,revision:$('revision').value.trim()}:brief();const data=await api('',{action:'generate',mode,brief:b,previousId:revision?current.id:undefined});lastBrief=b;storage.set('nb-preview-brief',JSON.stringify(b));storage.set('nb-preview-owned',data.id);show(data,true);status(revision?'Ajuste salvo. Confira a nova versão.':'Prévia salva! Você já pode copiar o link ou pedir um orçamento.');$('revision').value='';if(innerWidth<761)$('canvas').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){status(e.name==='TimeoutError'?'A geração demorou mais que o esperado. Tente novamente em instantes.':e.message);}finally{busy=false;$('generate').disabled=false;$('revise').disabled=false;$('loading').hidden=true;}}
$('brief').addEventListener('submit',e=>{e.preventDefault();generate()});$('revision-form').addEventListener('submit',e=>{e.preventDefault();generate(true)});
$('mobile').onclick=()=>{$('preview').classList.add('mobile');$('mobile').classList.add('selected');$('desktop').classList.remove('selected');$('mobile').setAttribute('aria-pressed','true');$('desktop').setAttribute('aria-pressed','false');};
$('desktop').onclick=()=>{$('preview').classList.remove('mobile');$('desktop').classList.add('selected');$('mobile').classList.remove('selected');$('desktop').setAttribute('aria-pressed','true');$('mobile').setAttribute('aria-pressed','false');};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(link());$('copy').textContent='Link copiado ✓';setTimeout(()=>$('copy').textContent='Copiar link',2500);}catch{status('Copie este link: '+link())}};
const examples={cafe:{name:'Aurora Café',kind:'site',prompt:'Uma cafeteria artesanal com cafés especiais e doces. Quero apresentar o ambiente, os serviços e facilitar encomendas.',theme:'light',accent:'orange'},barber:{name:'Barbearia Horizonte',kind:'landing',prompt:'Uma barbearia com cortes modernos, cuidado com a barba e atendimento com hora marcada. Quero uma página marcante para atrair clientes.',theme:'dark',accent:'gold'},system:{name:'Minha Operação',kind:'system',prompt:'Quero um sistema para organizar os atendimentos, acompanhar atividades e consultar os registros da minha pequena empresa.',theme:'light',accent:'blue'}};
document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>fill(examples[b.dataset.example]));
async function init(){try{const saved=storage.get('nb-preview-brief');if(saved)fill(JSON.parse(saved));}catch{}token=storage.get('nb-preview-session')||'';if(token&&Number(token.split('.')[1])<Date.now())token='';try{const cap=await api();mode=cap.aiEnabled?'ai':'template';$('mode-note').textContent=mode==='ai'?'✦ IA disponível · Sua descrição orienta textos e seções.':'Prévia por modelos disponível. A personalização por IA ainda não foi ativada.';$('generate').disabled=false;const id=new URLSearchParams(location.hash.slice(1)).get('p');if(id){const data=await api('?id='+encodeURIComponent(id));const own=storage.get('nb-preview-owned')===id&&!!token;lastBrief=own?brief():null;show(data,own);}}catch(e){$('mode-note').textContent='Não foi possível conectar ao studio. Atualize a página ou fale conosco.';status(e.message);}}
init();
